config/routes.rb
TalkingHandsApp::Application.routes.draw do

  devise_for :users

  devise_for :views

  resources :mentions
  resources :messages

  get "/users/:id", to: 'users#show', as: 'user'

  root :to => "home#index"

end

app/models/mention.rb
class Mention < ActiveRecord::Base
  attr_accessible :message_id, :tagged_user_id, :user_id

  belongs_to :message
  belongs_to :user

end

app/models/message.rb
class Message < ActiveRecord::Base

  attr_accessible :body, :user_id, :date, :quote

  belongs_to :user

  def self.fetch_latest_messages
    client = HipChat::Client.new(ENV['API_TOKEN'])
    room = client.rooms.select { |room| room.name.include?("WDI London December 2013") }.first
    history_string = room.history()
    history_hash = JSON.parse(history_string)
    messages = history_hash.first[1]

    messages.each do |message_hash|
      User.create_user_from_message_hash(message_hash)
      Message.create_message(message_hash)
    end
  end

  def self.create_message(message_hash)
    Message.create(
      date: message_hash['date'],
      user_id: User.where(name: message_hash['from']['name']).first.id,
      body: message_hash['message']
      )
  end

  def parse_mentions
    /\@[a-zA-Z]+/.match(self.body)
  end

  # def self.fetch_all_messages
  #   start_date = Date.parse('2013-12-16').to_s
  #   end_date = Date.today.to_s

  #   client = HipChat::Client.new(API_TOKEN)
  #   room = client.rooms.select { |room| room.name.include?("WDI London December 2013") }.first

  #   start_date.to_s.upto(end_date) do |date|
  #     history_string = room.history(date: date, timezone: 'GMT')
  #     history_hash = JSON.parse(history_string)
  #     messages = history_hash.first[1]

  #     messages.each do |message|

  #       User.create name: message['from']['name'], email: "#{message['from']['name'].gsub(/ /, "").downcase}@wdi4.com", password: "password", password_confirmation: "password" unless User.exists?(name: message['from']['name'])
  #       Message.create(
  #         date: message['date'],
  #         user_id: User.where(name: message['from']['name']).first.id,
  #         body: message['message']
  #         )
  #     end
  #     sleep(5)
  #   end
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  has_many :mentions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  def self.create_user_from_message_hash(message_hash)
    unless User.exists? name: message_hash['from']['name']
    User.create name: message_hash['from']['name'],
                email: "#{message_hash['from']['name'].gsub(/ /, "").downcase}@wdi4.com",
                password: "password",
                password_confirmation: "password"
    end
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


protected
  def after_sign_in_path_for(resource)
    messages_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/mentions_controller.rb
class MentionsController < ApplicationController
  before_filter :authenticate_user!
  # GET /mentions
  # GET /mentions.json
  def index
    @mentions = Mention.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mentions }
    end
  end

  # GET /mentions/1
  # GET /mentions/1.json
  def show
    @mention = Mention.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mention }
    end
  end

  # GET /mentions/new
  # GET /mentions/new.json
  def new
    @mention = Mention.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mention }
    end
  end

  # GET /mentions/1/edit
  def edit
    @mention = Mention.find(params[:id])
  end

  # POST /mentions
  # POST /mentions.json
  def create
    @mention = Mention.new(params[:mention])

    respond_to do |format|
      if @mention.save
        format.html { redirect_to @mention, notice: 'Mention was successfully created.' }
        format.json { render json: @mention, status: :created, location: @mention }
      else
        format.html { render action: "new" }
        format.json { render json: @mention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mentions/1
  # PUT /mentions/1.json
  def update
    @mention = Mention.find(params[:id])

    respond_to do |format|
      if @mention.update_attributes(params[:mention])
        format.html { redirect_to @mention, notice: 'Mention was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentions/1
  # DELETE /mentions/1.json
  def destroy
    @mention = Mention.find(params[:id])
    @mention.destroy

    respond_to do |format|
      format.html { redirect_to mentions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to user_path(@message.user), notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to user_path(@message.user), notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mentions_helper.rb
module MentionsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.haml
%p
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

.signup
=render 'shared/login'

.login_form
=render 'shared/signup'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HeadChat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<div id="logo"><%= link_to image_tag('/logo1.png'), messages_path %></div>

<div id="signin_corner">
  <% if current_user %>
      <%= current_user.email %>
      <%= link_to 'log out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'sign in', new_user_session_path %>
      <%= link_to 'sign up', new_user_registration_path %>
    <% end %>
</div>

</header>

<div id="container">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</div> <!-- closes container -->

</body>
</html>

app/views/mentions/_form.html.erb
<%= form_for(@mention) do |f| %>
  <% if @mention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mention.errors.count, "error") %> prohibited this mention from being saved:</h2>

      <ul>
      <% @mention.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :message_id %><br />
    <%= f.number_field :message_id %>
  </div>
  <div class="field">
    <%= f.label :tagged_user_id %><br />
    <%= f.number_field :tagged_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mentions/edit.html.erb
<h1>Editing mention</h1>

<%= render 'form' %>

<%= link_to 'Show', @mention %> |
<%= link_to 'Back', mentions_path %>

app/views/mentions/index.html.erb
<h1>Listing mentions</h1>

<table>
  <tr>
    <th>User</th>
    <th>Message</th>
    <th>Tagged user</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mentions.each do |mention| %>
  <tr>
    <td><%= mention.user_id %></td>
    <td><%= mention.message_id %></td>
    <td><%= mention.tagged_user_id %></td>
    <td><%= link_to 'Show', mention %></td>
    <td><%= link_to 'Edit', edit_mention_path(mention) %></td>
    <td><%= link_to 'Destroy', mention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mention', new_mention_path %>

app/views/mentions/new.html.erb
<h1>New mention</h1>

<%= render 'form' %>

<%= link_to 'Back', mentions_path %>

app/views/mentions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @mention.user_id %>
</p>

<p>
  <b>Message:</b>
  <%= @mention.message_id %>
</p>

<p>
  <b>Tagged user:</b>
  <%= @mention.tagged_user_id %>
</p>


<%= link_to 'Edit', edit_mention_path(@mention) %> |
<%= link_to 'Back', mentions_path %>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :quote %><br />
    <%= f.number_field :quote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div id="tile1A" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Tim Elder").first.messages.exists? %>
      <%= User.where(name: "Tim Elder").first.messages.last.body %>
    <% end %>
  </div>
  <img src="tim.svg">
  <% if User.where(name: "Tim Elder").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Tim Elder").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Tim', user_path(User.where(name: "Tim Elder").first.id) %></div>
</div>

<div id="tile1B" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Michael Pavling").first.messages.exists? %>
      <%= User.where(name: "Michael Pavling").first.messages.last.body %>
    <% end %>
  </div>
  <img src="michael.svg">
  <% if User.where(name: "Michael Pavling").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Michael Pavling").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Michael', user_path(User.where(name: "Michael Pavling").first.id) %></div>
</div>

<div id="tile1C" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Nikolas Mantis").first.messages.exists? %>
      <%= User.where(name: "Nikolas Mantis").first.messages.last.body %>
    <% end %>
  </div>
  <img src="nikolas.svg">
  <% if User.where(name: "Nikolas Mantis").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Nikolas Mantis").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Nikolas', user_path(User.where(name: "Nikolas Mantis").first.id) %></div>
</div>

<div id="tile1D" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Alex Pounds").first.messages.exists? %>
      <%= User.where(name: "Alex Pounds").first.messages.last.body %>
    <% end %>
  </div>
  <img src="alex.svg">
  <% if User.where(name: "Alex Pounds").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Alex Pounds").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Alex', user_path(User.where(name: "Alex Pounds").first.id) %></div>
</div>

<div id="tile2A" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Mark Randhawa").first.messages.exists? %>
      <%= User.where(name: "Mark Randhawa").first.messages.last.body %>
    <% end %>
  </div>
  <img src="mark.svg">
  <% if User.where(name: "Mark Randhawa").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Mark Randhawa").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Mark', user_path(User.where(name: "Mark Randhawa").first.id) %></div>
</div>

<div id="tile2B" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Imran Sulemanji").first.messages.exists? %>
      <%= User.where(name: "Imran Sulemanji").first.messages.last.body %>
    <% end %>
  </div>
  <img src="imran.svg">
  <% if User.where(name: "Imran Sulemanji").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Imran Sulemanji").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Imran', user_path(User.where(name: "Imran Sulemanji").first.id) %></div>
</div>

<div id="tile2C" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Kriszta Matyi").first.messages.exists? %>
      <%= User.where(name: "Kriszta Matyi").first.messages.last.body %>
    <% end %>
  </div>
  <img src="kriszta.svg">
  <% if User.where(name: "Kriszta Matyi").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Kriszta Matyi").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Kriszta', user_path(User.where(name: "Kriszta Matyi").first.id) %></div>
</div>

<div id="tile2D" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Clemens Kazda").first.messages.exists? %>
      <%= User.where(name: "Clemens Kazda").first.messages.last.body %>
    <% end %>
  </div>
  <img src="clems.svg">
  <% if User.where(name: "Clemens Kazda").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Clemens Kazda").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Clems', user_path(User.where(name: "Clemens Kazda").first.id) %></div>
</div>

<div id="tile3A" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Issam Sultan").first.messages.exists? %>
      <%= User.where(name: "Issam Sultan").first.messages.last.body %>
    <% end %>
  </div>
  <img src="issam.svg">
  <% if User.where(name: "Issam Sultan").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Issam Sultan").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Issam', user_path(User.where(name: "Issam Sultan").first.id) %></div>
</div>

<div id="tile3B" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Max Norton").first.messages.exists? %>
      <%= User.where(name: "Max Norton").first.messages.last.body %>
    <% end %>
  </div>
  <img src="maxn.svg">
  <% if User.where(name: "Max Norton").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Max Norton").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %> 
  <div class="tile_user"><%= link_to 'Max N.', user_path(User.where(name: "Max Norton").first.id) %></div>
</div>

<div id="tile3C" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Richill Tamakloe").first.messages.exists? %>
      <%= User.where(name: "Richill Tamakloe").first.messages.last.body %>
    <% end %>
  </div>
  <img src="richill.svg">
  <% if User.where(name: "Richill Tamakloe").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Richill Tamakloe").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Richill', user_path(User.where(name: "Richill Tamakloe").first.id) %></div>
</div>

<div id="tile3D" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Andy Born").first.messages.exists? %>
      <%= User.where(name: "Andy Born").first.messages.last.body %>
    <% end %>
  </div>
  <img src="andy.svg">
  <% if User.where(name: "Andy Born").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Andy Born").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>  
  <div class="tile_user"><%= link_to 'Andy', user_path(User.where(name: "Andy Born").first.id) %></div>
</div>

<div id="tile4A" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Laurent Curau").first.messages.exists? %>
      <%= User.where(name: "Laurent Curau").first.messages.last.body %>
    <% end %>
  </div>
  <img src="laurent.svg">
  <% if User.where(name: "Laurent Curau").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Laurent Curau").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Laurent', user_path(User.where(name: "Laurent Curau").first.id) %></div>
</div>

<div id="tile4B" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Jonny Adshead").first.messages.exists? %>
      <%= User.where(name: "Jonny Adshead").first.messages.last.body %>
    <% end %>
  </div>
  <img src="jonny.svg">
  <% if User.where(name: "Jonny Adshead").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Jonny Adshead").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Jonny', user_path(User.where(name: "Jonny Adshead").first.id) %></div>
</div>

<div id="tile4C" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Nico Castro").first.messages.exists? %>
      <%= User.where(name: "Nico Castro").first.messages.last.body %>
    <% end %>
  </div>
  <img src="nico.svg">
  <% if User.where(name: "Nico Castro").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Nico Castro").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %> 
  <div class="tile_user"><%= link_to 'Nico', user_path(User.where(name: "Nico Castro").first.id) %></div>
</div>

<div id="tile4D" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Thomas Martin").first.messages.exists? %>
      <%= User.where(name: "Thomas Martin").first.messages.last.body %>
    <% end %>
  </div>
  <img src="michael.svg">
  <% if User.where(name: "Thomas Martin").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Thomas Martin").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Tom', user_path(User.where(name: "Thomas Martin").first.id) %></div>
</div>

<div id="tile5A" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Max Perchik").first.messages.exists? %>
      <%= User.where(name: "Max Perchik").first.messages.last.body %>
    <% end %>
  </div>
  <img src="maxp.svg">
  <% if User.where(name: "Max Perchik").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Max Perchik").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Max P.', user_path(User.where(name: "Max Perchik").first.id) %></div>
</div>

<div id="tile5B" class='tile'>
  <div class="content_box">
    <% if User.where(name: "Paul Lainchbury").first.messages.exists? %>
      <%= User.where(name: "Paul Lainchbury").first.messages.last.body %>
    <% end %>
  </div>
  <img src="paul.svg">
  <% if User.where(name: "Paul Lainchbury").first.messages.exists? %>
    <button><%= link_to 'Save Quote', message_path(:id => User.where(name: "Paul Lainchbury").first.messages.last.id, :message => {:quote => "true"}), :method => :put %></button>
  <% end %>
  <div class="tile_user"><%= link_to 'Paul', user_path(User.where(name: "Paul Lainchbury").first.id) %></div>
</div>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @message.body %>
</p>

<p>
  <b>User:</b>
  <%= @message.user_id %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/shared/_form.html.erb
<%= form_for Message.new do |f| %>

  <div class="field">
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => @user.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :quote, :value => 'true' %>
  </div>
  <div class="actions" id="submit_btn">
    <%= f.submit "Add Quote" %>
  </div>
<% end %>

app/views/shared/_login.html.erb
<h2>Sign in</h2>

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "Sign in" %></div>
<% end %>

app/views/shared/_signup.html.erb
<h2 id='sign_up_title'>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :name %>
  <%= f.text_field :name, :autofocus => true, placeholder: 'name' %></div>

  <div><%= f.label :email %>
  <%= f.email_field :email, placeholder: 'email' %></div>

  <div><%= f.label :password %>
  <%= f.password_field :password, placeholder: 'password' %></div>

  <div><%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: 'password confirmation' %></div>

  <div><%= f.submit "Sign up" %></div>
<% end %>